# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Guardian project

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build_ios:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore

    - name: Build
      run: msbuild "./GuardianProject/GuardianProject.Ios/GuardianProject.iOS.csproj" /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
      
  build_android:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore

    - name: Build
      run: msbuild "./GuardianProject/GuardianProject.Android/GuardianProject.Android.csproj" /t:PackageForAndroid /p:Configuration=Debug
